title = My Site
base_url = http://localhost:4321
description = A new site built with Lattice.

[[collections]]
name = posts
dir = ./content/posts
schema = title:String,date:Date,description:Optional[String],tags:Optional[Array[String]],author:Optional[String],draft:Optional[Bool]
template = ./content/templates/page.html
page_size = 10
